print("             Welcome") 
print("--------------------------------")
print("|                              |")
print("|                              |")
print("|       Management Store       |")
print("|                              |")
print("|                              |")
print("--------------------------------")
